### ISSUE TITLE
AttributeError: 'Response' object has no attribute 'token'

### ISSUE THREAD

**Issue by luisfelipesdn12** [AndyCyberSec/pylovepdf#11]
I'm having this issue while "Watermark" tool

```python
Traceback (most recent call last):
  File "add_watermark.py", line 16, in <module>
    task = Watermark(secret_key,
  File "C:\Users\Usuário\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pylovepdf\tools\watermark.py", line 28, in __init__
    super(Watermark, self).__init__(public_key, True, verify_ssl, proxies)
  File "C:\Users\Usuário\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pylovepdf\task.py", line 42, in __init__
    self.auth()
  File "C:\Users\Usuário\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pylovepdf\task.py", line 50, in auth
    self._set_token(response.token)
AttributeError: 'Response' object has no attribute 'token'
```

**Comment by vasugamdha** [comment]
Please check the public key, which you pasted, doesn't have any extra space at the beginning or end.
Also, check that your public key is enabled in your developer account.

It's just something wrong with the parameters you passed.

**For a demo, you can try running the cells in this [colab](https://colab.research.google.com/drive/1zR63W018-nV5N3o0-NxBvxQElKqIjOLk?usp=sharing)**
